# Generated by Django 5.0.3 on 2024-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('professor', models.CharField(max_length=100, verbose_name='Professor')),
                ('state', models.CharField(choices=[('in_course', 'In Course'), ('done', 'Done')], default='in_course', max_length=20, verbose_name='State')),
                ('image', models.ImageField(null=True, upload_to='certifications', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['updated'],
            },
        ),
    ]
